[package]
name = "ndarray-npy"
version = "0.2.0"
authors = ["Jim Turner <ndarray-npy@turner.link>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/jturner314/ndarray-npy"
description = ".npy and .npz file format support for ndarray"
keywords = ["npy", "npz", "ndarray", "numpy", "array"]
categories = ["parser-implementations", "encoding", "science"]
readme = "README.md"

[badges]
travis-ci = { repository = "jturner314/ndarray-npy", branch = "master" }

[dependencies]
byteorder = "1.2"
ndarray = "0.11"
num = "0.1"
py_literal = "0.1"
quick-error = "1.2"
zip = { version = "0.4", default-features = false, optional = true }

[features]
default = ["compressed_npz_default"]
npz = ["zip"]
compressed_npz = ["npz", "zip/flate2"]
compressed_npz_default = ["compressed_npz", "zip/deflate"]
